# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LkEXgslKEKhBm5t+wtM0BuO73nYdl4GbuS/W7jXWr9NF8wi5HHL2k5jOPrLsn+LZTg9DiB6Eu1uLWMa8WGtlWzCaX9hTOw2dI85CShEMguvkFupeftgwbuBtW1eXSo01eb2p5DbOXTel9oX/AuzF44b1wUo3jH66ktH4+HcVJFg0oSkJUapsDgpQWmu2HxBWs6wl7DcNKRGj7lGuWiR5zGAKmTglw7EzlE3RzhKBajreFc10PaL4g2OYCAcRN3Ci+8x1IfjfArgu4nKrcvzht7wT3dA5IU89e3YJBkq452FW/JsHeSHXiCP+m/JNdaQg0mrVn4s4qDFP5jYhtJ0GqFGbakx5N2R86cgX8R80Y43rpJy7SVxZX7pSIXkQm4Tod3q07cf/JX1bLncA1Xhq3q8cFrTioWTZb+pO66B1yqkyNH/JaDCHLCuYGPhQUeFNwfblceOmiNzVWICDbB/OudrS0zsXCZM0GiOgm5XxVYIlzfQMmXNrxm2IqWrbZ0Zq8FvudU+PgAi6FjxCOZkR/XOWG+Gz6ylw9F/9NLVCyIn8LD8RdecvcNUiQag2qzTNVRmyIbml+C3osuc6zXM34qpiAcferyUhev8BaR+YkAn6RJBAU8m+pVHQPR05sKm6fD+esUtn8vPhrPDyAsFKbTy2MEX9QDNJXeRDyaVnoQ0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
